apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/OmarIRG/infra-repo.git
    targetRevision: master
    path: k8s/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
