apiVersion: v1
kind: Service
metadata:
  annotations:
    com.fortstak.updatable: "true"
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: app
