apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/compose-todo: "true"
        io.kompose.service: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_DATABASE
              value: todo
            - name: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_ROOT_USERNAME
          image: mongo:6
          livenessProbe:
            exec:
              command:
                - mongo
                - --quiet
                - --eval
                - db.runCommand('ping').ok
            failureThreshold: 5
            periodSeconds: 30
            timeoutSeconds: 5
          name: mongo
      restartPolicy: Always
