apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: watchtower
  name: watchtower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: watchtower
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/compose-todo: "true"
        io.kompose.service: watchtower
    spec:
      containers:
        - args:
            - --interval
            - "30"
            - --filter-label
            - com.fortstak.updatable
          image: containrrr/watchtower
          name: watchtower
      restartPolicy: Always
